#!/bin/bash
#In .bashrc

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

#To support emacs and byobu
export TERM=xterm-256color
source ~/.git-prompt.sh

PARENTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../ && pwd )"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PATH=/usr/local/go/bin:/home/vivek/android-studio/bin:/home/vivek/code/scbuild/bin:/home/vivek/sandbox/proset/bin:./:$PATH
export PATH

#BASH HISTORY
export JAVA_HOME="/home/vivek/jdk1.8.0_91"
export HISTSIZE=10000
export HISTFILESIZE=100000
export PROMPT_COMMAND="history -a; history -n; $PROMPT_COMMAND"
shopt -s histappend
# Combine multiline commands into one in history
shopt -s cmdhist
# Ignore duplicates, ls without options and builtin commands
HISTCONTROL=ignoredups
export HISTIGNORE="&:ls:[bf]g:exit"
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Prompt. http://misc.flogisoft.com/bash/tip_colors_and_formatting
# Custom shell prompt via kirsle.net/wizards/ps1.html
RED='\[\e[31m\]'
GREEN='\[\e[32m\]'
YELLOW='\[\e[33m\]'
BLUE='\[\e[34m\]'
BOLD_BLUE='\[\e[1;34m\]'
MAGENTA='\[\e[35m\]'
CYAN='\[\e[36m\]'
LIGHT_GRAY='\[\e[37m\]'
DARK_GRAY='\[\e[90m\]'
LIGHT_YELLOW='\[\e[93m\]'
NORMAL='\[\e[0m\]'
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUPSTREAM=1
GIT_PS1_DESCRIBE_STYLE=branch
GIT_STRING='$(__git_ps1 " [%s]")'
#END_CHARACTER=$'\u26A1' #Lightning
END_CHARACTER='$'
test -f /.dockerinit && END_CHARACTER='&'
PS1="${DARK_GRAY}[\A] ${GREEN}\u@${RED}\h:${YELLOW}\w${NORMAL}${CYAN}${GIT_STRING} ${LIGHT_YELLOW}${END_CHARACTER} ${NORMAL}"
export PS1

alias cd..='cd ../' # Go back 1 directory level (for fast typers)
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .3='cd ../../../'    # Go back 3 directory levels
alias .4='cd ../../../../' # Go back 4 directory levels
alias .5='cd ../../../../../'   # Go back 5 directory levels
alias .6='cd ../../../../../../'  # Go back 6 directory levels

alias p8='ping 8.8.8.8'

alias install='sudo apt-get install'
alias remove='sudo apt-get remove'
alias update='sudo apt-get update'
alias upgrade='sudo apt-get update && sudo apt-get upgrade'
alias droid='studio.sh'

#Ls improvements
alias ls='ls -F --color=auto'
alias ll='ls -hl'
alias lla='ls -ahl'
alias sl="ls"
alias l="ls"

# Make these commands ask before clobbering a file. Use -f to override.
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"

alias gs='git status '
alias ga='git add '
alias gaa='git add -A'
alias gb='git branch '
alias gbv='git branch -vv'
alias gc='git commit'
alias gcm='git commit -m'
alias gd='git diff'
alias gco='git checkout '
alias gfu='git fetch upstream'
alias gru='git rebase upstream/master'
alias gup='gfu && gru && gpo'
alias gl='git log --all --graph --decorate --oneline'
alias p='git pull'
alias gp='git push'
alias gpo='git push origin'
alias gm='git merge'
alias gr='git remote'
alias gsh='git stash'

alias gk='gitk --all&'
alias gx='gitx --all'

alias got='git '
alias get='git '
alias g='git'
alias d='docker'

alias sc='cd ~/code/'
alias sca='cd ~/code/scapi'
alias scr='cd ~/code/screact'
alias scw='cd ~/code/scweb'
alias scb='cd ~/code/scbuild'
alias box='cd ~/sandbox'
alias pro='cd ~/sandbox/proset'
alias dis='cd ~/sandbox/discourse'
alias lina='cd ~/sandbox/lina'
alias serve='python -m SimpleHTTPServer'
alias o='xdg-open'
alias emac='emacs -nw'
alias runemacs='emacs &'
alias dps='docker ps -a'
alias aws-add-creds='source $DIR/../revealed/keys/aws_iam_keys/sportscafe/export.sh'

# Autocomplete for 'g' as well
complete -o default -o nospace -F _git g

#Functions
extract () {
  if [ -f $1 ] ; then
      case $1 in
          *.tar.bz2)   tar xvjf $1    ;;
          *.tar.gz)    tar xvzf $1    ;;
          *.bz2)       bunzip2 $1     ;;
          *.rar)       rar x $1       ;;
          *.gz)        gunzip $1      ;;
          *.tar)       tar xvf $1     ;;
          *.tbz2)      tar xvjf $1    ;;
          *.tgz)       tar xvzf $1    ;;
          *.zip)       unzip $1       ;;
          *.Z)         uncompress $1  ;;
          *.7z)        7z x $1        ;;
          *)           echo "don't know how to extract '$1'..." ;;
      esac
  else
      echo "'$1' is not a valid file!"
  fi
}

function swap()
{ # Swap 2 filenames around, if they exist (from Uzi's bashrc).
    local TMPFILE=tmp.$$

    [ $# -ne 2 ] && echo "swap: 2 arguments needed" && return 1
    [ ! -e $1 ] && echo "swap: $1 does not exist" && return 1
    [ ! -e $2 ] && echo "swap: $2 does not exist" && return 1

    mv "$1" $TMPFILE
    mv "$2" "$1"
    mv $TMPFILE "$2"
}

mkcd() {
        if [ $# != 1 ]; then
                echo "Usage: mkcd <dir>"
        else
                mkdir -p $1 && cd $1
        fi
}
